### ISSUE TITLE
Best Practices When Using Route Constraints

### ISSUE THREAD

**Issue by metaskills** [fphilipe/warden-github-rails#17]
Using this gem for internal organization apps with easy GitHub authentication. Because of such, almost all of the apps routes are in constraint helpers like `github_authenticated`. I have found that this works against us in a few ways. Most notably, when using url helpers in mailers - specifically sent in the background with ActiveJob.

Is there a pattern to help with this? Only one I could think if was to not use constraint helpers and instead use an application filter. My experience with this gem is only in a recent Rails 5 edge app. I suspect behavior is the same for other versions too.

**Comment by fphilipe** [comment]
So the problem is basically that, at time of sending the emails, the routes you need are not defined since they're inside `github_authenticated` blocks, correct?

I see two possible alternatives:

1. Use `github_authenticate` instead of `github_authenticated`. I assume that this would be better anyways if you're including the link in the email for the user to click. With `github_authenticated` the user would click the link and, if they're not currently authenticated, get a 404. With `github_authentice` they would be redirected to GitHub and back.

2. Don't use the routes helper and have the logic in the controller.

Hope this helps.
